import { SignetGroup } from "../types/Signet";

export const signets: SignetGroup[] = [
  {
    slug: "HOT-Elysia",
    flameChaser: "Elysia",
    name: "Exclusive Signets",
    signets: [
      {
        slug: "HOT-Elysia-1",
        name: "Blessing of Divine Penalty",
        description:
          "In burst mode, Bombard costs 200% Herrscher Charge and every hit deals 400% ATK of bonus Lightning DMG.",
        type: "Exclusive",
      },
      {
        slug: "HOT-Elysia-2",
        name: "Blessing of Tsukuyomi",
        description:
          "Tap [ATK] after evasion to connect into Basic ATK sequence 4. Basic ATK sequence 4 boosts Total DMG by 40% for 5s.",
        type: "Exclusive",
      },
      {
        slug: "HOT-Elysia-3",
        name: "Blessing of Hazy Moon",
        description:
          "Basic ATK sequence 5 unleashes 3 bolts of thundering sanction each dealing 900% ATK of Lightning DMG on hit.",
        type: "Exclusive",
      },
      {
        slug: "HOT-Elysia-4",
        name: "Blessing of Mitama",
        description:
          "Max Herrscher Charge doubles and entering burst mode fully restores it. In burst mode, 75 Herrscher Charge is restored per second. Basic ATK sequence 5 restores 100 bonus Herrscher Charge.",
        type: "Exclusive",
      },
      {
        slug: "HOT-Elysia-5",
        name: "Blessing of Narukami",
        description:
          "Finisher unleashes 8 bolts of thundering sanction each dealing 900% ATK of Lightning DMG on hit.",
        type: "Exclusive",
      },
    ],
  },
  {
    slug: "HOR-Elysia",
    flameChaser: "Elysia",
    name: "Exclusive Signets",
    signets: [
      {
        slug: "HOR-Elysia-1",
        name: "Blessing of Creation",
        description:
          "In non-bike mode, Charged ATKs create 4 hover guns to attack, each dealing 160% ATK of Ice DMG on hit.",
        type: "Exclusive",
      },
      {
        slug: "HOR-Elysia-2",
        name: "Blessing of Truth",
        description:
          "Triggering Ultimate Evasion fully restores Konstruktyom. When Konstruktyom is below 120, any evasion can trigger Ultimate Evasion Skill.",
        type: "Exclusive",
      },
      {
        slug: "HOR-Elysia-3",
        name: "Blessing of Reason",
        description:
          "Every hit from hover guns reduces weapon active CD by 0.7s.",
        type: "Exclusive",
      },
      {
        slug: "HOR-Elysia-4",
        name: "Blessing of Wisdom",
        description:
          "In bike mode, Charged ATK inflicts a Structural Impact on enemies hit and deals 2250% ATK of Ice DMG.",
        type: "Exclusive",
      },
      {
        slug: "HOR-Elysia-5",
        name: "Blessing of Inspiration",
        description:
          "Triggering an Ultimate Evasion by any means inflicts a Structural Impact on enemies hit and deals 3750% ATK of Ice DMG.",
        type: "Exclusive",
      },
    ],
  },
  {
    slug: "HOFS-Elysia",
    flameChaser: "Elysia",
    name: "Exclusive Signets",
    signets: [
      {
        slug: "HOFS-Elysia-1",
        name: "Blessing of Reburn",
        description:
          "Triggering an Ultimate Evasion Skill removes Overheat and clears Heat.",
        type: "Exclusive",
      },
      {
        slug: "HOFS-Elysia-2",
        name: "Blessing of Tempered Warrior",
        description:
          "Aerial Combo ATKs reduce Ultimate Evasion Skill CD by 9s.",
        type: "Exclusive",
      },
      {
        slug: "HOFS-Elysia-3",
        name: "Blessing of Flamescion",
        description:
          "For every black hole created by the Herrscher of Flamescion, Valkyrie restores 25 HP per second and deals 30% bonus Total DMG.",
        type: "Exclusive",
      },
      {
        slug: "HOFS-Elysia-4",
        name: "Blessing of Starfire",
        description:
          "When a black hole created by the Herrscher of Flamescion disappears, a smaller black hole lasting 5s is generated, dealing 300% ATK of Fire DMG per second. CD: 3s.",
        type: "Exclusive",
      },
      {
        slug: "HOFS-Elysia-5",
        name: "Blessing of Heatflow",
        description:
          "Black holes generated by the Herrscher of Flamescion deal 75% bonus Fire DMG. Triggering Ultimate Evasion Skill creates an additional black hole dealing 1200% ATK of Fire DMG.",
        type: "Exclusive",
      },
    ],
  },
  {
    slug: "SN-Elysia",
    flameChaser: "Elysia",
    name: "Exclusive Signets",
    signets: [
      {
        slug: "SN-Elysia-1",
        name: "Blessing of Kindred",
        description: "Any mark resonance triggers the effect twice. CD: 5s.",
        type: "Exclusive",
      },
      {
        slug: "SN-Elysia-2",
        name: "Blessing of Vulnerable Duality",
        description:
          "Triggering Ultimate Evasion Skill reduces Ultimate CD by 40%.",
        type: "Exclusive",
      },
      {
        slug: "SN-Elysia-3",
        name: "Blessing of Union",
        description:
          "Within 12s after switching between Saule and Veliona, resonances of either Sunnebrands or Veilmarks trigger the resonance effects of both marks.",
        type: "Exclusive",
      },
      {
        slug: "SN-Elysia-4",
        name: "Blessing of Intergrowth",
        description:
          "Switching between Saule and Veliona restores full Ultimate Evasion Skill charges.",
        type: "Exclusive",
      },
      {
        slug: "SN-Elysia-5",
        name: "Blessing of Might of Duality",
        description:
          "Casting Ultimate creates a resonance field (up to 3 can be present). Resonances of Sunnebrands or Veilmarks deal 160% ATK of bonus Physical DMG to enemies within the field.",
        type: "Exclusive",
      },
    ],
  },
  {
    slug: "AKA-Elysia",
    flameChaser: "Elysia",
    name: "Exclusive Signets",
    signets: [
      {
        slug: "AKA-Elysia-1",
        name: "Blessing of Cold Moon",
        description:
          "Inflicting Ice Cell also creates a Frost Ring around the Valkyrie that lasts 6s and deals 180% ATK of Ice DMG per 0.3s to nearby enemies.",
        type: "Exclusive",
      },
      {
        slug: "AKA-Elysia-2",
        name: "Blessing of Frost Scythe",
        description:
          "Tap [ATK] after an evasion to hurl a Frost Guisarmier which spins for 5s, gathers enemies nearby, and deals 5400% ATK of Ice DMG. CD: 10s.",
        type: "Exclusive",
      },
      {
        slug: "AKA-Elysia-3",
        name: "Blessing of Winter Harvest",
        description:
          "Enemies recovering from Ice Cell are inflicted with 1 stack of Hypothermia.",
        type: "Exclusive",
      },
      {
        slug: "AKA-Elysia-4",
        name: "Blessing of Uranian Mirror",
        description:
          "Burst mode costs double SP to maintain. In Burst mode, Valkyrie deals 90% extra Total DMG.",
        type: "Exclusive",
      },
      {
        slug: "AKA-Elysia-5",
        name: "Blessing of Stellar Trails",
        description:
          "Inflicting Ice Cell in burst mode also creates a Frost Ring centered around the target, lasting 2s and dealing 480% ATK of Ice DMG per 0.3s to nearby enemies.",
        type: "Exclusive",
      },
    ],
  },
  {
    slug: "RI-Elysia",
    flameChaser: "Elysia",
    name: "Exclusive Signets",
    signets: [
      {
        slug: "RI-Elysia-1",
        name: "Blessing of Torch",
        description:
          "When a Combo ATK that consumes KE hits an enemy, all gun turrets fire a laser beam at the target to deal Physical DMG equal to the number of Combo ATK stacks x 1600% ATK.",
        type: "Exclusive",
      },
      {
        slug: "RI-Elysia-2",
        name: "Blessing of Dawn",
        description:
          "At full KE, the next Combo ATK consumes all of it to constitute 4 stacks and additionally fire 4 homing missiles dealing 3600% ATK of Physical DMG in total.",
        type: "Exclusive",
      },
      {
        slug: "RI-Elysia-3",
        name: "Blessing of Blossom",
        description:
          "Homing missiles restore 2 SP on hit. Basic ATK Sequence 6 additionally fires 4 homing missiles, each dealing 450% ATK of Physical DMG.",
        type: "Exclusive",
      },
      {
        slug: "RI-Elysia-4",
        name: "Blessing of Prosperity",
        description:
          "Tap [ATK] after an evasion to dash to enemies and deliver an aerial kick, which can be connected into Basic ATK Sequence 4. Basic ATK Sequence 6 restores 150 KE every time it lands.",
        type: "Exclusive",
      },
      {
        slug: "RI-Elysia-5",
        name: "Blessing of Fertility",
        description:
          "Ultimate replenishes 40 light bullets for every gun turret and boosts their Tech Level by 1 (caps at 3). Each turret restores KE at a rate of Tech Level x 30 per second.",
        type: "Exclusive",
      },
    ],
  },
  {
    slug: "VG-Elysia",
    flameChaser: "Elysia",
    name: "Exclusive Signets",
    signets: [
      {
        slug: "VG-Elysia-1",
        name: "Blessing of Impetus",
        description:
          "Entering Sprint triggers Stage 2 and until Sprint ends, attacks cost 40 Resolve more on hit to deal 200% ATK of Fire DMG. CD: 0.1s.",
        type: "Exclusive",
      },
      {
        slug: "VG-Elysia-2",
        name: "Blessing of Gloria",
        description:
          "The last hit of Charged ATK or Throw ATK inflicts Magnifica Mark on enemies, which explodes after a short delay, dealing 1500% ATK of Fire DMG.",
        type: "Exclusive",
      },
      {
        slug: "VG-Elysia-3",
        name: "Blessing of Sol",
        description:
          "Within 3s of performing an Ultimate Evasion, Basic ATK Sequence 5 or the last hit of Charged ATK inflicts Magnifica Mark on enemies, which explodes after a short delay, dealing 1200% ATK of Fire DMG.",
        type: "Exclusive",
      },
      {
        slug: "VG-Elysia-4",
        name: "Blessing of Battle Song",
        description:
          "Weapon Actives deal 200% bonus Total DMG. Hitting an enemy with a Charged ATK in Aura Ignis resets the Weapon Active CD.",
        type: "Exclusive",
      },
      {
        slug: "VG-Elysia-5",
        name: "Blessing of Triumph",
        description:
          "Triggering an Ultimate Evasion Skill or detonating Magnifica Mark restores 15 SP.",
        type: "Exclusive",
      },
    ],
  },
  {
    slug: "PV-Elysia",
    flameChaser: "Elysia",
    name: "Exclusive Signets",
    signets: [
      {
        slug: "PV-Elysia-1",
        name: "Blessing of Dark Wings",
        description:
          "When Ultimate Evasion Skill is triggered, Oz unleashes dark lightning that deals 4200% ATK of Lightning DMG.",
        type: "Exclusive",
      },
      {
        slug: "PV-Elysia-2",
        name: "Blessing of Retribution",
        description:
          "QTE creates a small lightning field which lasts 5s and deals 3x200% ATK of Lightning DMG per second to enemies within it.",
        type: "Exclusive",
      },
      {
        slug: "PV-Elysia-3",
        name: "Blessing of Nightfall",
        description:
          "Weapon Actives deal 200% bonus Total DMG. Summoning Oz with Charged ATK or casting Ultimate refills 2 weapon active charges.",
        type: "Exclusive",
      },
      {
        slug: "PV-Elysia-4",
        name: "Blessing of Fate",
        description:
          "When hitting an enemy with a weapon active, Oz unleashes dark lightning to deal 2000% ATK of Lightning DMG.",
        type: "Exclusive",
      },
      {
        slug: "PV-Elysia-5",
        name: "Blessing of Midnight",
        description:
          "During Ultimate, Oz lingers for 7s after the arrow rain. Every 7 hits from Oz on enemies within the Ultimate range summons dark lightning that deals 1500% ATK of Lightning DMG.",
        type: "Exclusive",
      },
    ],
  },
  {
    slug: "ELY-Elysia",
    flameChaser: "Elysia",
    name: "Exclusive Signets",
    signets: [
      {
        slug: "ELY-Elysia-1",
        name: "Blessing of Purity",
        description:
          "Ultimate lasts 15s longer. While Ultimate is active, a wave of ricochet occurs under Flawless Dome every second. The ricochets triggered in this way only ricochet 3 times but deal 130% ATK of Physical DMG (DMG source: Ultimate).",
        type: "Exclusive",
      },
      {
        slug: "ELY-Elysia-2",
        name: "Blessing of Zenith",
        description:
          "While Ultimate is active, each ricochet deals 15% ATK of bonus Physical DMG on hit. Every wave of ricochet reduces weapon active's CD by 0.6s.",
        type: "Exclusive",
      },
      {
        slug: "ELY-Elysia-3",
        name: "Blessing of Love",
        description:
          "While Ultimate is active, Charged Shot: Cupid's Bolt consumes 100% bonus Infatuation and deals 700% ATK of bonus Physical DMG.",
        type: "Exclusive",
      },
      {
        slug: "ELY-Elysia-4",
        name: "Blessing of Benevolence",
        description:
          "Infatuation is fully restored when Ultimate Evasion Skill is triggered. If Infatuation drops below 100 after using Charged Shot: Cupid's Bolt, you can consume 1 Ultimate Evasion charge to trigger Ultimate Evasion Skill.",
        type: "Exclusive",
      },
      {
        slug: "ELY-Elysia-5",
        name: "Blessing of Beauty",
        description:
          "Using weapon active restores 1 additional Ultimate Evasion charge. Enemies take 25% bonus Total DMG when a Crystalline Seed is attached to them.",
        type: "Exclusive",
      },
    ],
  },
  {
    slug: "BKE-Elysia",
    flameChaser: "Elysia",
    name: "Exclusive Signets",
    signets: [
      {
        slug: "BKE-Elysia-1",
        name: "Blessing of Holy Lance",
        description: "During Basic ATK SEQ 4, tap ATK repeatedly.",
        type: "Exclusive",
      },
      {
        slug: "BKE-Elysia-2",
        name: "Blessing of Formation",
        description: "Basic ATK SEQ 5 creates a 3-sec Grav Singularity.",
        type: "Exclusive",
      },
      {
        slug: "BKE-Elysia-3",
        name: "Blessing of Glory",
        description: "In Burst mode, Weapon Active has 70% shorter CD.",
        type: "Exclusive",
      },
      {
        slug: "BKE-Elysia-4",
        name: "Blessing of Paragon",
        description:
          "Casting Weapon Active shortens Ultimate CD. Ultimate grants 5 stacks of Paragon.",
        type: "Exclusive",
      },
      {
        slug: "BKE-Elysia-5",
        name: "Blessing of Gambit",
        description:
          "Triggering Retaliation or Ultimate Evasion boosts Physical DMG.",
        type: "Exclusive",
      },
    ],
  },
  {
    slug: "LK-Elysia",
    flameChaser: "Elysia",
    name: "Exclusive Signets",
    signets: [
      {
        slug: "LK-Elysia-1",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "LK-Elysia-2",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "LK-Elysia-3",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "LK-Elysia-4",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "LK-Elysia-5",
        name: "",
        description: "",
        type: "Exclusive",
      },
    ],
  },
  {
    slug: "VB-Elysia",
    flameChaser: "Elysia",
    name: "Exclusive Signets",
    signets: [
      {
        slug: "1VB-Elysia-",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "VB-Elysia-2",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "VB-Elysia-3",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "VB-Elysia-4",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "VB-Elysia-5",
        name: "",
        description: "",
        type: "Exclusive",
      },
    ],
  },
  {
    slug: "NYX-Elysia",
    flameChaser: "Elysia",
    name: "Exclusive Signets",
    signets: [
      {
        slug: "NYX-Elysia-1",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "NYX-Elysia-2",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "NYX-Elysia-3",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "NYX-Elysia-4",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "NYX-Elysia-5",
        name: "",
        description: "",
        type: "Exclusive",
      },
    ],
  },
  {
    slug: "IO-Elysia",
    flameChaser: "Elysia",
    name: "Exclusive Signets",
    signets: [
      {
        slug: "IO-Elysia-1",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "IO-Elysia-2",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "IO-Elysia-3",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "IO-Elysia-4",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "IO-Elysia-5",
        name: "",
        description: "",
        type: "Exclusive",
      },
    ],
  },
  {
    slug: "RVN-Elysia",
    flameChaser: "Elysia",
    name: "Exclusive Signets",
    signets: [
      {
        slug: "RVN-Elysia-1",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "RVN-Elysia-2",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "RVN-Elysia-3",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "RVN-Elysia-4",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "RVN-Elysia-5",
        name: "",
        description: "",
        type: "Exclusive",
      },
    ],
  },
  {
    slug: "HOS-Elysia",
    flameChaser: "Elysia",
    name: "Exclusive Signets",
    signets: [
      {
        slug: "HOS-Elysia-1",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "HOS-Elysia-2",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "HOS-Elysia-3",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "HOS-Elysia-4",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "HOS-Elysia-5",
        name: "",
        description: "",
        type: "Exclusive",
      },
    ],
  },
  {
    slug: "TP-Elysia",
    flameChaser: "Elysia",
    name: "Exclusive Signets",
    signets: [
      {
        slug: "TP-Elysia-1",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "TP-Elysia-2",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "TP-Elysia-3",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "TP-Elysia-4",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "TP-Elysia-5",
        name: "",
        description: "",
        type: "Exclusive",
      },
    ],
  },
  {
    slug: "SNS-Elysia",
    flameChaser: "Elysia",
    name: "Exclusive Signets",
    signets: [
      {
        slug: "SNS-Elysia-1",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "SNS-Elysia-2",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "SNS-Elysia-3",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "SNS-Elysia-4",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "SNS-Elysia-5",
        name: "",
        description: "",
        type: "Exclusive",
      },
    ],
  },
  {
    slug: "DA-Elysia",
    flameChaser: "Elysia",
    name: "Exclusive Signets",
    signets: [
      {
        slug: "DA-Elysia-1",
        name: "Blessing of Stars",
        description: "Ultimate deals bonus Total DMG.",
        type: "Exclusive",
      },
      {
        slug: "DA-Elysia-2",
        name: "Blessing of Gale",
        description: "In Astral Harness, all attacks ignite enemies.",
        type: "Exclusive",
      },
      {
        slug: "DA-Elysia-3",
        name: "Blessing of Sheen",
        description: "Ultimates do not suspend Astrum consumption.",
        type: "Exclusive",
      },
      {
        slug: "DA-Elysia-4",
        name: "Blessing of Halo",
        description:
          "Ultimates deal bonus Fire DMG within 8 meters of target hit.",
        type: "Exclusive",
      },
      {
        slug: "DA-Elysia-5",
        name: "Blessing of Brilliance",
        description: "Ultimate costs no SP and restores SP.",
        type: "Exclusive",
      },
    ],
  },
  {
    slug: "SW-Elysia",
    flameChaser: "Elysia",
    name: "Exclusive Signets",
    signets: [
      {
        slug: "SW-Elysia-1",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "SW-Elysia-2",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "SW-Elysia-3",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "SW-Elysia-4",
        name: "",
        description: "",
        type: "Exclusive",
      },
      {
        slug: "SW-Elysia-5",
        name: "",
        description: "",
        type: "Exclusive",
      },
    ],
  },
  {
    slug: "kevin",
    flameChaser: "Kevin",
    name: "Signet of Deliverance",
    signets: [
      {
        slug: "kevin-1",
        name: "Goblet of the Giver",
        description: "Ultimate boosts Total DMG by 35% for 5s.",
        type: "Normal",
      },
      {
        slug: "kevin-2",
        name: "Pendant of the Watcher",
        description: "Ultimate boosts Physical DMG by 30% for 5s.",
        type: "Normal",
      },
      {
        slug: "kevin-3",
        name: "Brand of the Undead",
        description: "Ultimate boosts Elemental DMG by 30% for 5s.",
        type: "Normal",
      },
      {
        slug: "kevin-4",
        name: "Mask of the Predator",
        description: "Ultimate boosts Physical Breach by 25% for 5s.",
        type: "Normal",
      },
      {
        slug: "kevin-5",
        name: "Artifact of the Inhibitor",
        description: "Ultimate boosts Elemental Breach by 20% for 5s.",
        type: "Normal",
      },
      {
        slug: "kevin-6",
        name: "Rochet of the Pilgrim",
        description: "Ultimate restores 3 SP per second for 5s.",
        type: "Normal",
      },
      {
        slug: "kevin-7",
        name: "Blade of the Deliverer",
        description:
          "Ultimate triggers Final Battle status during which all buffs provided by Normal Signets of Deliverance increase by 50% for 5s.",
        type: "Core",
      },
      {
        slug: "kevin-8",
        name: "Flock of the Deliverer",
        description:
          "Final Battle is also considered burst mode. Total DMG increases by 20% in burst mode.",
        nexus: "kevin-7",
        type: "Enhanced",
      },
      {
        slug: "kevin-9",
        name: "Crusade of the Deliverer",
        description:
          "After 3s into Final Battle, all buffs provided by Normal Signets of Deliverance increase by 90% instead of 50%.",
        nexus: "kevin-7",
        type: "Enhanced",
      },
      {
        slug: "kevin-10",
        name: "Echo of the Deliverer",
        description:
          "Duration of Final Battle and all buffs provided by Normal Signets of Deliverance are extended to 8s.",
        nexus: "kevin-7",
        type: "Enhanced",
      },
      {
        slug: "kevin-11",
        name: "Shadow of the Deliverer",
        description:
          "When ultimate or burst mode attacks hit enemies 50 times, gain War of Deliverance which activates all Deliverance signets.",
        type: "Core",
      },
      {
        slug: "kevin-12",
        name: "Dream of the Deliverer",
        description:
          "In War of Deliverance, all buffs provided by Normal Signets of Deliverance increase by 50%.",
        nexus: "kevin-11",
        type: "Enhanced",
      },
      {
        slug: "kevin-13",
        name: "Resolve of the Deliverer",
        description:
          "For every ultimate or burst mode attack hit, gain 0.5% Total Damage, max 50%.",
        nexus: "kevin-11",
        type: "Enhanced",
      },
      {
        slug: "kevin-14",
        name: "Triumph of the Deliverer",
        description:
          "When entering War of Deliverance, ignore enemy defence and elemental resists for 6s.",
        nexus: "kevin-11",
        type: "Enhanced",
      },
    ],
  },
];
